name: Build CursorOverlay x86

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install 32-bit MinGW
      run: |
        choco install mingw -y

    - name: Build x86
      run: |
        i686-w64-mingw32-g++ main.cpp -o CursorOverlay.exe -mwindows -lgdi32 -luser32

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: CursorOverlay-x86
        path: CursorOverlay.exe
