name: Build CursorOverlay

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        g++ main.cpp -o CursorOverlay.exe -mwindows -m32

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: CursorOverlay
        path: CursorOverlay.exe
